spring:
  application:
    name: demo-application
  config:
    import: 'aws-parameterstore:'

cloud:
  aws:
    credentials:
      profile-name: stratospheric
    region:
      static: eu-central-1
    stack:
      auto: false # Automatic stack detection
    sns:
      enabled: true
    sqs:
      enabled: true
