name: Email Forward Handler

on:
  push:
    paths:
      - 'utility/email/**'
      - '.github/workflows/email-forward-handler.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and deploy AWS lambda
    concurrency: deploy-forwarding-lambda
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # Must be Java 11 as AWS Lambda currently only supports Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build and deploy the function
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        working-directory: utility/email
        if: github.ref == 'refs/heads/main'
        run: |
          sudo npm install -g serverless
          npm install
          ./gradlew buildZip
          serverless deploy
